       0:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       1:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       2:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       3:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       4:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       5:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       6:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       7:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       8:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       9:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       a:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       b:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       c:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       d:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       e:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
       f:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      10:	00 00                	dw     0x0000
      12:	00 00                	dw     0x0000
      14:	00 00                	dw     0x0000
      16:	00 00                	dw     0x0000
      18:	00 00                	dw     0x0000
      1a:	00 00                	dw     0x0000
      1c:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      1d:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      1e:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      1f:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      20:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      21:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      22:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      23:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      24:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      25:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      26:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      27:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      28:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      29:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      2a:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      2b:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      2c:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      2d:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      2e:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      2f:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      30:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'
      31:	00                   	db     0x00                                                         ; dec:   0, chr: '\0'